# sign.yml
name: Sign Image
permissions:
  id-token: write
  packages: write
  contents: read
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # AWS 변수
  AWS_REGION: ap-northeast-2
  AWS_ECR_ACCOUNT_ID: 310330934744

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    permissions:
      contents: write
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install Notation CLI
        run: |
          wget https://d2hvyiie56hcat.cloudfront.net/linux/amd64/installer/deb/latest/aws-signer-notation-cli_amd64.deb
          sudo dpkg -i aws-signer-notation-cli_amd64.deb
          notation version
          notation plugin ls
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'
          registries: ${{ env.AWS_ECR_ACCOUNT_ID }}

      - name: Build Image
        run: |
          cd 01_docker/04_nodejs_blue_service
          IMAGE=${{ env.AWS_ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/blue-service:latest
          docker build -t $IMAGE .
          docker push $IMAGE
          echo "IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE)" >> $GITHUB_ENV
          echo ${{ env.IMAGE_DIGEST }}
      - name: Sign Image
        run: |
          aws ecr get-login-password | notation login \
          --username AWS \
          --password-stdin ${{ env.AWS_ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
          notation sign \
          ${{ env.AWS_ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_DIGEST }} \
          --plugin com.amazonaws.signer.notation.plugin \
          --id arn:aws:signer:${{ env.AWS_REGION }}:${{ env.AWS_ECR_ACCOUNT_ID }}:/signing-profiles/notation_test
      # - name: Push Chart
      #   run: |
      #     echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u $ --password-stdin
      #     helm push hello-world-0.1.1.tgz oci://ghcr.io/${{ github.repository_owner }}
    #   - name: Install Notation CLI
    #     run: |
          